# Generated by Django 4.0.4 on 2023-01-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moviedate',
            new_name='Moviedata',
        ),
    ]
